language: python
python:
  - "3.3"

install:
  - pip install tox
  - pip install coverage coveralls

script:
  - tox -r

notifications:
  slack: kawaz:Dh59b2T0KqhQnBR6qHYUDdpn

after_success:
  - coverage report
  - coveralls
