language: python
python:
  - "3.3"
env:
  - DJANGO_VERSION=1.6
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -qr requirements.txt --use-mirrors
  - pip install -qr requirements-test.txt --use-mirrors
script:
  - python setup.py test
