language: python
python:
  - "3.3"
env:
  - DJANGO_VERSION=1.6
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -qr requirements.txt
  - pip install -qr requirements-test.txt
script:
  - python setup.py test
