language: python
python:
  - "3.3"

before_install:
  - git submodule update --init --recursive

install:
  - pip install tox
  - pip install coverage coveralls
  - npm install

script:
  - npm run build
  - tox -r

notifications:
  slack: kawaz:Dh59b2T0KqhQnBR6qHYUDdpn

after_success:
  - coverage report
  - coveralls
