language: python
python:
  - '3.3'

before_install:
  - openssl aes-256-cbc
    -K $encrypted_f141a85a02d3_key
    -iv $encrypted_f141a85a02d3_iv
    -in config/credentials.json.enc
    -out config/gcal/credentials.json -d
  - git submodule update --init --recursive

install:
  - pip install tox
  - pip install coverage coveralls
  - npm install

script:
  - npm run build
  - tox -r

after_success:
  - coverage report
  - coveralls

notifications:
  slack: kawaz:Dh59b2T0KqhQnBR6qHYUDdpn
